// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "RoadHelper",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "RoadHelper",
            targets: ["AppModule"],
            bundleIdentifier: "com.marco.Toxapex",
            teamIdentifier: "9ZR7S424TH",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "This App needs access to the camera for the Attention Assistant to function."),
                .contacts(purposeString: "This app requires access to your contacts to let you select and add emergency contacts quickly.")
            ],
            appCategory: .travel
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageModes: [.version("6")]
)
